
version: "3.8"

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    restart: unless-stopped

    ports:
      - "2222:2222"
      - "2223:2223"

    volumes:
        - ../logs/cowrie:/cowrie/cowrie-git/var/log/cowrie
        

    networks:
      - honeynet

networks:
  honeynet:
    external: true